# Generated by Django 5.2.8 on 2025-11-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_admin',
            new_name='tbl_adminreg',
        ),
    ]
