# Generated by Django 5.2.8 on 2025-11-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_adminreg',
            old_name='admin_pasword',
            new_name='admin_password',
        ),
    ]
