# Generated by Django 5.2.8 on 2025-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_rename_admin_pasword_tbl_adminreg_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
                ('level_duration', models.CharField(max_length=50)),
            ],
        ),
    ]
