# Generated by Django 5.2.8 on 2025-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
