# Generated by Django 5.2.8 on 2025-12-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcategory_name', models.CharField(max_length=50)),
            ],
        ),
    ]
