# Generated by Django 5.2.8 on 2025-12-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_jobcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
