# Generated by Django 5.2.8 on 2026-01-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_mark', models.CharField(max_length=50)),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_examtype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_level')),
            ],
        ),
    ]
