# Generated by Django 5.2.8 on 2026-01-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_question', models.CharField(max_length=50)),
                ('question_file', models.FileField(upload_to='Assets/Admindocs/Questions/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_exam')),
            ],
        ),
    ]
