# Generated by Django 5.2.8 on 2026-01-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_question',
            name='question_file',
            field=models.FileField(null=True, upload_to='Assets/Admindocs/Questions/'),
        ),
        migrations.CreateModel(
            name='tbl_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_option', models.CharField(max_length=50)),
                ('option_status', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_question')),
            ],
        ),
    ]
