# Generated by Django 5.2.8 on 2026-01-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_tbl_question_question_file_tbl_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_level',
            name='level_duration',
            field=models.IntegerField(default=10),
        ),
    ]
