# Generated by Django 5.2.8 on 2026-01-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_tbl_level_level_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=50)),
                ('notification_details', models.CharField(max_length=50)),
                ('notification_file', models.FileField(null=True, upload_to='Assests/Admindocs/Exam/')),
                ('notification_todate', models.DateField()),
            ],
        ),
    ]
