# Generated by Django 5.2.8 on 2026-02-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_crashcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crashcourse_title', models.CharField(max_length=50)),
                ('crashcourse_details', models.CharField(max_length=50)),
                ('crashcourse_photo', models.FileField(null=True, upload_to='Assets/Admindoc/course/')),
                ('crashcourse_duration', models.CharField(max_length=50)),
                ('crashcourse_lastdate', models.DateField()),
            ],
        ),
    ]
