
from django.urls import path, include
from Admin import views
app_name="Admin"

urlpatterns = [
    path('Homepage/', views.Homepage,name="Homepage"),
    path('Adminregistration/', views.Adminregistration,name="Adminregistration"),
    path('District/', views.District,name="District"),
    path('Category/',views.Category,name="Category"),
    path('Place/',views.Place,name="Place"),
    path('Subcategory/',views.Subcategory,name="Subcategory"),
    path('deldistrict/<int:id>',views.deldistrict,name="deldistrict"),
    path('delcategory/<int:cid>',views.delcategory,name="delcategory"),
    path('editcategory/<int:id>',views.editcategory,name="editcategory"),
    path('editdistrict/<int:id>',views.editdistrict,name="editdistrict"),
    path('deladmin/<int:id>',views.deladmin,name="deladmin"),
    path('editadmin/<int:id>',views.editadmin,name="editadmin"),
    path('delplace/<int:id>',views.delplace,name='delplace'),
    path('editplace/<int:id>',views.editplace,name='editplace'),
    path('delsub/<int:id>',views.delsub,name='delsub'),
    path('editsub/<int:id>',views.editsub,name='editsub'),
    path('Userlist/',views.Userlist,name="Userlist"),
    path('Recruiterverification/',views.Recruiterverification,name="Recruiterverification"),
    path('acceptrecruiter/<int:id>',views.acceptrecruiter,name="acceptrecruiter"),
    path('rejectrecruiter/<int:id>',views.rejectrecruiter,name="rejectrecruiter"),
    path('Level/',views.Level,name="Level"),
    path('dellevel/<int:id>',views.dellevel,name='dellevel'),
    path('editlevel/<int:id>',views.editlevel,name='editlevel'),
    path('Jobtype/',views.Jobtype,name="Jobtype"),
    path('deljt/<int:id>',views.deljt,name='deljt'),
    path('editjt/<int:id>',views.editjt,name='editjt'),
    path('Jobcategory/',views.Jobcategory,name="Jobcategory"),
    path('deljc/<int:id>',views.deljc,name='deljc'),
    path('editjc/<int:id>',views.editjc,name='editjc'),
    path('Examtype/',views.Examtype,name="Examtype"),
    path('delext/<int:id>',views.delext,name='delext'),
    path('editext/<int:id>',views.editext,name='editext'),
    path('Notes/',views.Notes,name='Notes'),
    path('notedel/<int:id>',views.notedel,name='notedel'),
    path('Viewnotes/',views.Viewnotes,name='Viewnotes'),
    path('acceptnotes/<int:id>',views.acceptnotes,name='acceptnotes'),
    path('rejectnotes/<int:id>',views.rejectnotes,name='rejectnotes'),
    path('Examination/',views.Examination,name='Examination'),
    path('dele/<int:id>',views.dele,name='dele'),
    path('Question/<int:id>',views.Question,name='Question'),
    path('delq/<int:qid>/<int:id>',views.delq,name='delq'),
    path('Addoption/<int:id>',views.Addoption,name='Addoption'),
    path('delo/<int:did>/<int:id>',views.delo,name='delo'),
    path('Viewcomplaint/',views.Viewcomplaint,name="Viewcomplaint"),
    path('Reply/<int:id>',views.Reply,name="Reply"),
    path('logout/',views.logout,name="logout"),
    path('Notification/',views.Notification,name="Notification"),
    path('deln/<int:id>',views.deln,name='deln'),
    path('Viewfeedback/',views.Viewfeedback,name="Viewfeedback"),
    path('Crashcourse/',views.Crashcourse,name="Crashcourse"),
    path('delcourse/<int:id>',views.delcourse,name='delcourse'),
    path('Viewclass/',views.Viewclass,name='Viewclass'),
    path('acceptc/<int:id>',views.acceptc,name='acceptc'),
    path('rejectc/<int:id>',views.rejectc,name='rejectc'),



]
