# Generated by Django 5.2.8 on 2025-11-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_rename_admin_pasword_tbl_adminreg_admin_password'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(max_length=50)),
                ('recruiter_email', models.CharField(max_length=50)),
                ('recruiter_password', models.CharField(max_length=50)),
                ('recruiter_address', models.CharField(max_length=50)),
                ('recruiter_photo', models.FileField(upload_to='Assets/Recruiterdocs/')),
                ('recruiter_contact', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
