# Generated by Django 5.2.8 on 2025-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_recruiter',
            name='recruiter_licence',
            field=models.FileField(default=11.05, upload_to='Assets/Recruiterdocs/Licence/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_recruiter',
            name='recruiter_proof',
            field=models.FileField(default=0, upload_to='Assets/Recruiterdocs/Proof/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_recruiter',
            name='recruiter_photo',
            field=models.FileField(upload_to='Assets/Recruiterdocs/Photo/'),
        ),
    ]
