# Generated by Django 5.2.8 on 2025-11-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_recruiter_recruiter_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_recruiter',
            name='recruiter_status',
            field=models.IntegerField(default=0),
        ),
    ]
