# Generated by Django 5.2.8 on 2025-12-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_examtype'),
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_date', models.DateField(auto_now_add=True)),
                ('notes_title', models.CharField(max_length=50)),
                ('notes_details', models.CharField(max_length=50)),
                ('nots_file', models.FileField(upload_to='Assets/Userdocs/File/')),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_examtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userreg')),
            ],
        ),
    ]
