# Generated by Django 5.2.8 on 2025-12-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_notes',
            old_name='nots_file',
            new_name='notes_file',
        ),
    ]
