# Generated by Django 5.2.8 on 2025-12-31 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('User', '0003_rename_nots_file_tbl_notes_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_notes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userreg'),
        ),
    ]
