# Generated by Django 5.2.8 on 2025-12-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notes',
            name='notes_status',
            field=models.IntegerField(default=0),
        ),
    ]
