# Generated by Django 5.2.8 on 2026-01-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('Recruiter', '0001_initial'),
        ('User', '0005_tbl_notes_notes_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('apply_status', models.IntegerField(default=0)),
                ('apply_file', models.FileField(upload_to='Assets/Userdocs/File/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.tbl_job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userreg')),
            ],
        ),
    ]
