# Generated by Django 5.2.8 on 2026-01-09 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
    ]
