# Generated by Django 5.2.8 on 2026-01-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
