# Generated by Django 5.2.8 on 2026-01-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_tbl_question_question_file_tbl_option'),
        ('User', '0008_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationhead_date', models.DateField(auto_now_add=True)),
                ('examinationhead_status', models.IntegerField(default=0)),
                ('examinationhead_total_mark', models.CharField(max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_exam')),
            ],
        ),
    ]
