# Generated by Django 5.2.8 on 2026-01-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_tbl_question_question_file_tbl_option'),
        ('User', '0009_tbl_examinationhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationbody_correct_answer', models.CharField(max_length=50)),
                ('examinationbody_myanswer', models.CharField(max_length=50)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examinationhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examinationhead')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_question')),
            ],
        ),
    ]
