# Generated by Django 5.2.8 on 2026-01-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_examinationbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examinationhead',
            name='exam',
        ),
        migrations.DeleteModel(
            name='tbl_examinationbody',
        ),
        migrations.DeleteModel(
            name='tbl_examinationhead',
        ),
    ]
