# Generated by Django 5.2.8 on 2026-01-10 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_tbl_question_question_file_tbl_option'),
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('User', '0011_remove_tbl_examinationhead_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userreg')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examinationanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationanswers_statusq', models.IntegerField(default=0)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='Admin.tbl_option')),
                ('myanswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myanswer', to='Admin.tbl_option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_question')),
                ('examinationbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examinationbody')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_timmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timmer', models.TimeField()),
                ('timmer_status', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_exam')),
            ],
        ),
    ]
