# Generated by Django 5.2.8 on 2026-01-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('User', '0012_tbl_examinationbody_tbl_examinationanswers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('recruiter_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_from', to='Guest.tbl_recruiter')),
                ('recruiter_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_to', to='Guest.tbl_recruiter')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_userreg')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_userreg')),
            ],
        ),
    ]
