# Generated by Django 5.2.8 on 2026-01-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_timmer',
            name='exam',
        ),
        migrations.DeleteModel(
            name='tbl_examinationanswers',
        ),
        migrations.DeleteModel(
            name='tbl_examinationbody',
        ),
        migrations.DeleteModel(
            name='tbl_timmer',
        ),
    ]
