# Generated by Django 5.2.8 on 2026-01-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('User', '0016_tbl_examinationbody_tbl_examinationanswers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userreg'),
        ),
    ]
