# Generated by Django 5.2.8 on 2025-12-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_tbl_examtype'),
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_details', models.CharField(max_length=50)),
                ('job_lastdate', models.DateField()),
                ('job_date', models.DateField(auto_now_add=True)),
                ('job_experience', models.CharField(max_length=50)),
                ('job_requirment', models.CharField(max_length=50)),
                ('jobcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_jobcategory')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_jobtype')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_recruiter')),
            ],
        ),
    ]
