# Generated by Django 5.2.8 on 2026-02-19 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_recruiter_recruiter_status'),
        ('Recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_careerguidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerguidence_details', models.CharField(max_length=50)),
                ('careerguidence_photo', models.FileField(null=True, upload_to='Assets/Recruiterdocs/class/')),
                ('careerguidence_date', models.DateField()),
                ('careerguidence_time', models.TimeField()),
                ('careerguidence_class', models.CharField(max_length=50)),
                ('careerguidence_status', models.IntegerField(default=0)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_recruiter')),
            ],
        ),
    ]
